# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ah < Formula
  desc "Artifact Hub command line tool"
  homepage "https://github.com/artifacthub/hub"
  version "1.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artifacthub/hub/releases/download/v1.12.0/ah_1.12.0_macos_amd64.tar.gz"
      sha256 "f56736ec09aabd9d7dffb6029758f7fa5740268166dc583a10ab0841c0d5a3c0"

      def install
        bin.install "ah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artifacthub/hub/releases/download/v1.12.0/ah_1.12.0_macos_arm64.tar.gz"
      sha256 "060bf4b747827479a611608d7f2bad8c403ca8361d5d3178b1041d5f61ffe717"

      def install
        bin.install "ah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/artifacthub/hub/releases/download/v1.12.0/ah_1.12.0_linux_amd64.tar.gz"
      sha256 "7830e6954bd50467966c4d0f2c2e9d470fd9b378b2f4d1e559d73775955934ad"

      def install
        bin.install "ah"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifacthub/hub/releases/download/v1.12.0/ah_1.12.0_linux_arm64.tar.gz"
      sha256 "58f962066b3ce38846298d358503ea6645f1b752a2961ada4e290374997f57c8"

      def install
        bin.install "ah"
      end
    end
  end
end
