# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ah < Formula
  desc "Artifact Hub command line tool"
  homepage "https://github.com/artifacthub/hub"
  version "1.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/artifacthub/hub/releases/download/v1.14.0/ah_1.14.0_macos_amd64.tar.gz"
      sha256 "d179fe89a8eedfaf87c6edc71f15e01e5700950af53c9b4cb3d577af5dc01ccc"

      def install
        bin.install "ah"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/artifacthub/hub/releases/download/v1.14.0/ah_1.14.0_macos_arm64.tar.gz"
      sha256 "84b678f57f68843611793dc724ffdf91928cfe786d19fb12ee6d181edb57b763"

      def install
        bin.install "ah"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/artifacthub/hub/releases/download/v1.14.0/ah_1.14.0_linux_arm64.tar.gz"
      sha256 "9dc463e024b252794d425099ee4dcd1803dc8d2bf6703920ef3dda76d0c36720"

      def install
        bin.install "ah"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/artifacthub/hub/releases/download/v1.14.0/ah_1.14.0_linux_amd64.tar.gz"
      sha256 "78c8b96375308a381fba612ba44a89140ea306908f698ca412cb30a10a8f71c9"

      def install
        bin.install "ah"
      end
    end
  end
end
