# This file was generated by GoReleaser. DO NOT EDIT.
cask "ah" do
  version "1.23.0"

  on_macos do
    on_intel do
      sha256 "70324ad24a8416a949431e70442265828a19e7eba69113244e9d4b39cf4a07b2"
      url "https://github.com/artifacthub/hub/releases/download/v#{version}/ah_#{version}_macos_amd64.tar.gz"
    end
    on_arm do
      sha256 "b3d98551e28e6809a1efbaff70b498e4822be83c322b94e48f0f750bc7362cde"
      url "https://github.com/artifacthub/hub/releases/download/v#{version}/ah_#{version}_macos_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "062dbd849d8d6de688627baca9042b3dd2ce4cf6c9767fba1d4d0b4e8476c18c"
      url "https://github.com/artifacthub/hub/releases/download/v#{version}/ah_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fa0ab126b36d3b5a105be230a89dcc4185782a3ed53a3b51c7389c2f6b72cb8"
      url "https://github.com/artifacthub/hub/releases/download/v#{version}/ah_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ah"
  desc "Artifact Hub command line tool"
  homepage "https://github.com/artifacthub/hub"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ah"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ah"]
    end
  end

  # No zap stanza required

end
